### PR TITLE
Added skew options to graphic objects #111

### PR DESCRIPTION
**Pull request by shaehn**
skewX and skewY are available in all graphic objects. Units are in angle degrees.

### CODE REVIEW

**Comment by chunyenHuang** [comment]
It seems to me that some of the changes are already in the current version, can you either update the source branch or create a new PR to just show the changes? Thanks.

**Comment by shaehn** [comment]
Hmm.... I am not sure what I should do here.  This was the code that got bunched up with the encrypt code. So when you merged the pull request for 1.8.9 it only got the encryption part but not this for skew, but now this PR has both sets of code in it? I am sorry, but I find this GIT stuff really annoying. I have worked with lots of source code control systems but this one has been nothing but a headache for me. So how do we throw this PR out? I will have to make sure I save the changed files  from this branch I created, then burn that branch and start over with a new PR. Is that the thought process here? Let me know. Step by step please.  So far the only successful path I have seen with GIT is to make one change for one PR, then wait for you to merge before I can make changes for other PR's. Totally serial and painstakingly long process. There has got to be a better way. How do you work on multiple PR's to the same baseline?

**Comment by chunyenHuang** [comment]
Technically the PR will update to show the difference, but sometimes github can not show correctly. If you pull the master and re-create a PR, it should just show the difference only.

**Comment by chunyenHuang** [comment]
If you want to work PR in chain, you can branch out from the previous one instead from the master.

**Pull request closed without merging**
