### PR TITLE
Added page index for overlay

### PR DESCRIPTION
**Pull request by landerson6678**
Using the options parameters in .drawImage and page details in inMetadata you can now choose what page index you want for a pdf overlay

### CODE REVIEW

**Comment by shaehn** [comment]
@landerson6678, the use of the option name 'page_index' is confusing to me. After looking at the code changes, it would appear that it is not really the 0 based index that hummus uses, but rather the actual page number. If this is the case, I would think the option name should just be 'page'.

**Comment by landerson6678** [comment]
Sounds good I'll change it to 0 based (saw meta data and thought 1's based) and change page_index to page

**Comment by landerson6678** [comment]
Should I change it to 0's based but keep page_index or move to 1's based and name it page? .editPage() is 1's based so it might be confusing swapping between 0's and 1's

**Comment by shaehn** [comment]
Yes, you did as desired, using page numbers instead of page indices. Thanks.

**Comment by chunyenHuang** [comment]
Looks good to me, I will fix some format and merge the codes

**Pull request merged**
