### PR TITLE
Added CMYK and Gray color space access to other drawable figures

### PR DESCRIPTION
**Pull request by shaehn**
Polygons, Circles, Rectangles and Lines now can be drawn with CMYK, RGB, and Gray colors.

### CODE REVIEW

**Comment by chunyenHuang** [comment]
awesome, thanks. Can you also check the test files?

**Comment by shaehn** [comment]
I can add code to the color.js file, but how do I actually test that it works? This has always been a wrinkle for me in this GIT world. Can you teach me how to fish, or show me where to go to learn how to verify tests? Thanks.

**Comment by chunyenHuang** [comment]
You may run 
```
mocha tests/color.js
```
and check the output pdf files in `tests/output/color-*.pdf`

**Comment by shaehn** [comment]
Ok, thanks for the information. I will work on this tomorrow.

**Comment by shaehn** [comment]
I updated the color tests to include all the drawing interfaces. There is now one more file, color-all.pdf which gives examples of implicit colorspace specifications and shows the default colors when specifications are bad. It's ready to publish after you look at it.

**Pull request merged**
