### PR TITLE
#87 Typescript init

### PR DESCRIPTION
**Pull request by chunyenHuang**
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/21ef5dc3f0171ac2453d309ff0bb80ad05be1222/types/hummus-recipe/index.d.ts

### CODE REVIEW

**Comment by chunyenHuang** [comment]
#87

**Comment by shaehn** [comment]
John, The only thing I notice at first glance is that you have _AnotOptions_, which looks like a typo. I would suggest spelling it out completely like you did for the rest of the options -> **AnnotationOptions**. 
Reads better. Other improvements will have to come from actually using the definitions and see who complains.

**Comment by she11sh0cked** [comment]
> The only thing I notice at first glance is that in index.d.ts you have AnotOptions, which looks like a typo. I would suggest spelling it out completely like you did for the rest of the options -> AnnotationOptions.
> or AnnotateOptions if you want it shorter. That will read better. Other improvements will have to come from actually using the definitions and see who complains.

Yeah, I wrote the definition based on the [documentation](https://chunyenhuang.github.io/hummusRecipe/Recipe.html) and a few things I found out on the way. Something like [this](https://hastebin.com/vekinutosi.js) (may or may not actually work because I wrote this on my phone) for example is not in there and would need to be added.

**Comment by she11sh0cked** [comment]
> The only thing I notice at first glance is that in index.d.ts you have AnotOptions, which looks like a typo. I would suggest spelling it out completely like you did for the rest of the options -> AnnotationOptions.
> or AnnotateOptions if you want it shorter. That will read better. Other improvements will have to come from actually using the definitions and see who complains.

Are you sure you want the interface "IAnnot[..]" for the method "annot" be named "IAnnotation[..]"? I think that could confuse people because of the mismatch.

**Comment by shaehn** [comment]
It still is a typo as given. AnotOptions should have two ‘n’ letters. That is, AnnotOptions.

**Review by shaehn — APPROVED** [review]

**Pull request merged**
