### PR TITLE
Migrated van hummus to muhammara

### PR DESCRIPTION
**Pull request by sjaakieb**
Changed the dependency from hummus to muhammara(https://github.com/julianhille/MuhammaraJS). Is related to issue #186

### CODE REVIEW

**Comment by chunyenHuang** [comment]
Thanks, but I would like to provide the options for both since the repo is designed for hummusJS

**Comment by sjaakieb** [comment]
@chunyenHuang what would be the benefit of that since muhammara is just a fork of hummus?

**Comment by chunyenHuang** [comment]
`2.0.0` start using `muhammara`

**Comment by mhio** [comment]
fyi https://github.com/julianhille/MuhammaraJS/issues/38
I get some odd output from node-pre-gyp on the console after moving to 2.0.0.
```
this changes julianhille/MuhammaraJS/releases/download/{version}
{node_abi}-{platform}-{arch}-{libc}.tar.gz
{module_name}-v{version}-{node_abi}-{platform}-{arch}.tar.gz
```
Seems releases might be coming from a dev box rather than CI which is mildy concerning.

**Comment by julianhille** [comment]
Yes this is correct the `npm publish` command is currently issued locally.
Need to setup a github action, sorry for the inconvenience, will try to do that shortly for more transperency and less errors.

**Pull request merged**
